#修改端口防止冲突
server:
  port: 9090

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/project?serverTimezone=GMT%2b8
    username: root
    password: 123456
# 扫描该路径下所有的的xml文件(把我们编写的动态sql语句纳入springboot的管控下)
mybatis:
  mapper-locations: classpath:mapper/*.xml
#  configuration:
## 在控制台输出拼接之后的sql语句
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true

# 阿里沙箱支付的相关配置
alipay:
  appId: 2021000119675710
  appPrivateKey: MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCSQ2yBpTx0ZDp2cdRMS9VwbYnhuUgXtyEqm0JSx+LchuKU7QM86UyCMr9DOBpdN26BVMBKr30v9BvCJAHdXZbI593Fc0quqk4olCb/IzAOSrwsrLW8GoV+f6ejD1ZMSUuw3d14Y9gP5cZD5gsJiDAmzpyIHjNdFMbfcQouDNtyD0fINob9JRPD0eNYxUJHzuWEeAXpVsL7coYndTq3CeNgSWLiLH70d0Yd1OBBxPnJUwlaHADhi0k/P1FCReY24dmxpqqPSpNpO8qSswFHM8v8h+Buqhr/MSXHATW25Mn6dC90N8dg+e3+h6Yoa9fcLbTBYsBgE5BUcRMEJ91aJRg3AgMBAAECggEAdD3bnYmp60LA5+N9ewmF3y1fOKLdNePYGxl7c3jixqr4pq1bNmyf3pXgRdbvtQfZ7jViAblIv/S8nuWpCbpYnOER8tu3DevR5BQijgD0L1ecB9FXOeDGGYvwufn1dvmFi1I4snZ/f9r4YHwSZ4fx5NWtt8xwu9hIWcpn8cNMIG/qdDKUosuDQDqcg4mO8DjsWjBfk2wRKFlc3GOSGQtbhd86aU62dGFt+XqLhbjTScnChWL++r9tkUvOoEAEG7YLIfOXBKezjGaPkyUEkMSnWql/0Fs85o0mk5XD/FTRiv3PzzWTQjn3Q+3qnG9HFL4TraHT/7r/M6n75TclLBEwuQKBgQDMHq28jxqP5PPhIN1hTSqgrhD0v2sQ37fGKyZ+vyDHMmPIgcKrC4c3r8Xrd7S/Q822mjqy0Jzph05cd4Lhz2B9bESVGIjWUg495Gc/Vw0adcDr0iuK8v+Gb/8on9gO1+j1oAiA/IgKkiToDZ2pUjlLt7Bs6yOUm33vnxJ1uHRu0wKBgQC3cD1Q8B8yiGXF8wuxQU0O99TG4PkvRxUgcIlPMMkEWFlt9i8YHE9w2+g1/vFQHD7JM4sS2dikmCiiW04cdHhve+RvkzifaHjh7IM149F3TSOhl482ra6mkPgsi7vaxiTrlg/B5gYiK1lWZAK2E3UKMZgrgm3jKeWC0cZQoM76jQKBgFqzEx4jNHlWEewqT1SKFnP5hL1MRUXlMuLSj7NoOCdrQ51300lvwPDEoRyFP4JxnXoTRBvqyJ6YKgC6diTiogx5TGw3z630HjHwSNSDWOY2BriC1ihS26ogH/AsPrQxymlCaCTwkX6o+89FJZZ0W9NCVxm+zjudcDNGqsw2Xz5TAoGBALGx42PNR5tO76+icdgiVsBCKPcCpcA7jmafPRPeQUuZPgA8M4CapAXCsJ3lueMNiXCkInt/VdKTpwEni3IbDTOJg07mATrCHB9WWgBREO8NZY+6XjvsYTvvQMj+D1qtCMTB17/P0G83KNJ8DPhNvtnCExNKxKICSta/2Ojv7bBdAoGAdl6fmjkZodNuBezfLM367/cf9FpDb6VUNQz0cW7X0IHbmCGu4MxyqG1098x8NFL+9iBKt5jplNf+D5IF75IjfFx5ApIOhYyE19jDyF2aVWCX9hs+2RMCnWO5giG5XNt+0lPYvQEesnC0uxF8cSm3bcWx+kryyU9o5Ao2XNgsL7E=
  alipayPublicKey: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA3OYJMWM3iDUIT1GTztmlRznwt8uIt/9cHv2cOWLyCgjzFOd3pS0oIgr2E2AItdcozhRgbfRkYze8NRlPsXQmTOFpinXLgDdAeCdVokl+WN5k7+LptICv4L9PS3VWb/PkzmGah2SsCJI/NH2DiC739D8m1IApksSBH2pZv4i/AYQbICCCTZNnaCAVc/Z6EmpDClz4cWmby6M0P3rcis022g4LlsvwfMCCX+htb5NQHX3H4+GJQHh3I1pHvIu/PAVjk7NeA6XneeQIvD3bKqpSUDuduBGDBmV9UT/y1t4AqRP6tVxi0fpNvDXXZIkOEZuXliCa//jA8NA+dFGzE8+Y6wIDAQAB
  notifyUrl:
